### ISSUE TITLE
A quick code review

### ISSUE THREAD

**Issue by janipalsamaki** [UniversityofHelsinki/mece-php#2]
## Class reference is not case-sensitive

`NotificationMessage.php`:260 (`new \StdClass();`)
## Typos (some of them)

`Message.php`:74 ("an string" -> "a string")

`Message.php`:78 ("langauges")

`Message.php`:96 ("an recipient" -> "a recipient")

`MultilingualStringValue.php`:38 ("langauges")

`VersionTrait.php`:14 ("accross")

`MultilingualStringValueTest`:48 ("Langauge")
## Possibility to simplify code

`NotificationMessage.php` (several places):

`DateTime` instances can be compared directly as of PHP 5.2.2.

Instead of:

`if ($deadline->getTimestamp() > $this->getExpiration()->getTimestamp()) {`

One could write:

`if ($deadline > $this->getExpiration()) {`
## Possibly redundant (obvious) comments that provide no extra value

The most basic setter methods would not probably require an explanation that states the obvious, for example:

```
/**
 * Getter method for getting link.
 * @return MultilingualStringValue
 */
 public function getLink() {
   return $this->link;
 }
```

This might be enough:

```
/**
 * @return MultilingualStringValue
 */
 public function getLink() {
   return $this->link;
 }
```

**Comment by mikaelkundert** [comment]
Thanks for review! Will work on these soon!

**Comment by mikaelkundert** [comment]
Fixed, thx!
